# 200_load_roadsafety_datasets_2015-2016

## Purpose
In this notebook we will begin our analysis of the UK Road Safety Data. Primarily, we will focus on loading and reviewing the datasets for the 2015 – 2016 acident records, and save an aggregate dataset of all of these accidents.

## Notebook Contents:
* __1:__ Loading the Datasets
   
* __2:__ Combining the Datasets
    * __2.1:__ 2016
    * __2.2:__ 2015
    * __2.3:__ Check Datasets 2015 and 2016 Match


* __3:__ Aggregate 2015 and 2016 Dataframes

* __4:__ Saving the Dataset
    
* __5:__ Saving Data to a Pickle File

* __6:__ Creating a Data Dictionary

## Datasets
__Input:__ 
* Accidents_2015.csv    (raw 2015 accident report data)
* Accidents_2016.csv    (raw 2016 accident report data)
* Vehicles_2015.csv     (raw 2015 data on vehicles involved in accidents)
* Vehicles2016.csv      (raw 2016 data on vehicles involved in accidents)


__Output:__ 
* 200_all_2015-2016.pkl    (data for UK Road Safety data for years 2015-2016)

In [1]:
import os
import sys
import hashlib
import pandas as pd
import numpy as np

module_path = os.path.abspath(os.path.join('../../data/..'))
if module_path not in sys.path:
    sys.path.append(module_path)
    
from src.helpers import data_dictionary
    
%matplotlib inline

# 1. Loading the Datasets
The datasets are all in a standard csv format, so we will read these in using Pandas `read_csv` method.

As we have such a large amount of data we decided to read in the different datasets separately. This would make it easier for us to clean each dataset as well as improve time efficency.

In [2]:
Accidents_2015 = pd.read_csv('../../data/raw/Accidents_2015.csv')
Accidents_2015.shape

C:\Users\Ciara\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2698: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

(140056, 32)

In [3]:
Accidents_2015.head()

,Accident_Index,Location_Easting_OSGR,Location_Northing_OSGR,Longitude,Latitude,Police_Force,Accident_Severity,Number_of_Vehicles,Number_of_Casualties,Date,...,Pedestrian_Crossing-Human_Control,Pedestrian_Crossing-Physical_Facilities,Light_Conditions,Weather_Conditions,Road_Surface_Conditions,Special_Conditions_at_Site,Carriageway_Hazards,Urban_or_Rural_Area,Did_Police_Officer_Attend_Scene_of_Accident,LSOA_of_Accident_Location
0,201501BS70001,525130.0,180050.0,-0.198465,51.505538,1,3,1,1,12/01/2015,...,0,0,4,1,1,0,0,1,1,E01002825
1,201501BS70002,526530.0,178560.0,-0.178838,51.491836,1,3,1,1,12/01/2015,...,0,0,1,1,1,0,0,1,1,E01002820
2,201501BS70004,524610.0,181080.0,-0.205590,51.514910,1,3,1,1,12/01/2015,...,0,1,4,2,2,0,0,1,1,E01002833
3,201501BS70005,524420.0,181080.0,-0.208327,51.514952,1,3,1,1,13/01/2015,...,0,0,1,1,2,0,0,1,2,E01002874
4,201501BS70008,524630.0,179040.0,-0.206022,51.496572,1,2,2,1,09/01/2015,...,0,5,1,2,2,0,0,1,2,E01002814

In [4]:
Accidents_2016 = pd.read_csv('../../data/raw/Accidents_2016.csv')
Accidents_2016.shape

C:\Users\Ciara\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2698: DtypeWarning: Columns (31) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

(136621, 32)

In [5]:
Vehicles_2015 = pd.read_csv('../../data/raw/Vehicles_2015.csv')
Vehicles_2015.shape

(257845, 23)

In [6]:
Vehicles_2016 = pd.read_csv('../../data/raw/Vehicles2016.csv')
Vehicles_2016.head()

,Accident_Index,Vehicle_Reference,Vehicle_Type,Towing_and_Articulation,Vehicle_Manoeuvre,Vehicle_Location-Restricted_Lane,Junction_Location,Skidding_and_Overturning,Hit_Object_in_Carriageway,Vehicle_Leaving_Carriageway,...,Journey_Purpose_of_Driver,Sex_of_Driver,Age_of_Driver,Age_Band_of_Driver,Engine_Capacity_(CC),Propulsion_Code,Age_of_Vehicle,Driver_IMD_Decile,Driver_Home_Area_Type,Vehicle_IMD_Decile
0,2016010000005,1,8,0,6,0,0,0,0,0,...,1,1,51,8,-1,-1,-1,3,1,3
1,2016010000005,2,2,0,18,0,0,0,0,0,...,6,1,23,5,124,1,4,4,1,4
2,2016010000006,1,9,0,18,0,2,2,10,1,...,6,2,36,7,1461,2,1,10,1,10
3,2016010000008,1,9,0,18,0,4,5,0,0,...,6,1,24,5,1390,1,5,8,1,8
4,2016010000016,1,11,0,18,0,1,0,0,0,...,1,1,55,8,6692,2,7,9,1,9

We now have each of our 4 datasets, two datasets containing accident reports and vehicles involved in 2015, the other two for 2016. The Accident datasets both have 32 of the same columns. The Vehicle datasets both contain 23 columns.

We acknowledge that this wasn't a great example of DRY (_do not repeat yourself_) coding. However, due to the size of our datasets we have chosen to load 4 datasets in this notebook, and the remaining 4 in the previous notebook. As a result, we needed to manually read the datasets which were relevant to this notebook

# 2. Combining the Datasets

We have decided to use the merge method to combine our vehicle and accident datasets for both year groups (2015 and 2016).

We have chosen to use the merge method due to the row difference in each dataset. As there may have been multiple vehicles involved in one accident, we will do a check to ensure that our merged dataset contains only rows which have a corresponding accident index in both datasets.

We will therefore merge based on the "Accident_Index" column.

_Note:_ The 'Accident_Index' is a number which represents an accident.

## 2.1 2016

In [7]:
pd.set_option('display.max_columns', 54) # This will enable us to view all rows
All_2016 = pd.merge(Accidents_2016, Vehicles_2016, on='Accident_Index') 
All_2016.head()

,Accident_Index,Location_Easting_OSGR,Location_Northing_OSGR,Longitude,Latitude,Police_Force,Accident_Severity,Number_of_Vehicles,Number_of_Casualties,Date,Day_of_Week,Time,Local_Authority_(District),Local_Authority_(Highway),1st_Road_Class,1st_Road_Number,Road_Type,Speed_limit,Junction_Detail,Junction_Control,2nd_Road_Class,2nd_Road_Number,Pedestrian_Crossing-Human_Control,Pedestrian_Crossing-Physical_Facilities,Light_Conditions,Weather_Conditions,Road_Surface_Conditions,Special_Conditions_at_Site,Carriageway_Hazards,Urban_or_Rural_Area,Did_Police_Officer_Attend_Scene_of_Accident,LSOA_of_Accident_Location,Vehicle_Reference,Vehicle_Type,Towing_and_Articulation,Vehicle_Manoeuvre,Vehicle_Location-Restricted_Lane,Junction_Location,Skidding_and_Overturning,Hit_Object_in_Carriageway,Vehicle_Leaving_Carriageway,Hit_Object_off_Carriageway,1st_Point_of_Impact,Was_Vehicle_Left_Hand_Drive?,Journey_Purpose_of_Driver,Sex_of_Driver,Age_of_Driver,Age_Band_of_Driver,Engine_Capacity_(CC),Propulsion_Code,Age_of_Vehicle,Driver_IMD_Decile,Driver_Home_Area_Type,Vehicle_IMD_Decile
0,2016010000005,519310.0,188730.0,-0.279323,51.584754,1,3,2,1,01/11/2016,3,02:30,28,E09000005,3,4006,6,30.0,0,-1,-1,0,0,0,5,1,1,0,0,1,1,E01000543,1,8,0,6,0,0,0,0,0,0,3,1,1,1,51,8,-1,-1,-1,3,1,3
1,2016010000005,519310.0,188730.0,-0.279323,51.584754,1,3,2,1,01/11/2016,3,02:30,28,E09000005,3,4006,6,30.0,0,-1,-1,0,0,0,5,1,1,0,0,1,1,E01000543,2,2,0,18,0,0,0,0,0,0,1,1,6,1,23,5,124,1,4,4,1,4
2,2016010000006,551920.0,174560.0,0.184928,51.449595,1,3,1,1,01/11/2016,3,00:37,18,E09000004,3,207,6,30.0,9,4,6,0,0,0,4,1,1,0,0,1,1,E01000375,1,9,0,18,0,2,2,10,1,0,4,1,6,2,36,7,1461,2,1,10,1,10
3,2016010000008,505930.0,183850.0,-0.473837,51.543563,1,3,1,1,01/11/2016,3,01:25,26,E09000017,3,4020,1,30.0,1,4,3,4020,0,0,4,1,1,0,0,1,1,E01033725,1,9,0,18,0,4,5,0,0,0,1,1,6,1,24,5,1390,1,5,8,1,8
4,2016010000016,527770.0,168930.0,-0.164442,51.404958,1,3,1,1,01/11/2016,3,09:15,22,E09000024,3,217,6,30.0,3,2,3,217,0,0,1,1,1,0,0,1,1,E01003379,1,11,0,18,0,1,0,0,0,0,0,1,1,1,55,8,6692,2,7,9,1,9

Below you can see that the datasets have successfull merged as there are a total of 54 columns. This is because the datasets have been merged on a common column (therefore 55-1).

In [8]:
print("Accidents_2016 dimensions: {}".format(Accidents_2016.shape))
print("Vehicles_2016 dimensions: {}".format(Vehicles_2016.shape))
print("All_2016 dimensions: {}".format(All_2016.shape))

Accidents_2016 dimensions: (136621, 32)
Vehicles_2016 dimensions: (252500, 23)
All_2016 dimensions: (252500, 54)

## 2.2 2015

Similarly, we will combine all of the data for the year 2015 based on the common column 'Accident_Index'. This includes the Accidents and Vehicles data for this year.

In [9]:
pd.set_option('display.max_columns', 54) # To view all columns
All_2015 = pd.merge(Accidents_2015, Vehicles_2015, on='Accident_Index')
All_2015.head()

,Accident_Index,Location_Easting_OSGR,Location_Northing_OSGR,Longitude,Latitude,Police_Force,Accident_Severity,Number_of_Vehicles,Number_of_Casualties,Date,Day_of_Week,Time,Local_Authority_(District),Local_Authority_(Highway),1st_Road_Class,1st_Road_Number,Road_Type,Speed_limit,Junction_Detail,Junction_Control,2nd_Road_Class,2nd_Road_Number,Pedestrian_Crossing-Human_Control,Pedestrian_Crossing-Physical_Facilities,Light_Conditions,Weather_Conditions,Road_Surface_Conditions,Special_Conditions_at_Site,Carriageway_Hazards,Urban_or_Rural_Area,Did_Police_Officer_Attend_Scene_of_Accident,LSOA_of_Accident_Location,Vehicle_Reference,Vehicle_Type,Towing_and_Articulation,Vehicle_Manoeuvre,Vehicle_Location-Restricted_Lane,Junction_Location,Skidding_and_Overturning,Hit_Object_in_Carriageway,Vehicle_Leaving_Carriageway,Hit_Object_off_Carriageway,1st_Point_of_Impact,Was_Vehicle_Left_Hand_Drive?,Journey_Purpose_of_Driver,Sex_of_Driver,Age_of_Driver,Age_Band_of_Driver,Engine_Capacity_(CC),Propulsion_Code,Age_of_Vehicle,Driver_IMD_Decile,Driver_Home_Area_Type,Vehicle_IMD_Decile
0,201501BS70001,525130.0,180050.0,-0.198465,51.505538,1,3,1,1,12/01/2015,2,18:45,12,E09000020,5,0,6,30,3,4,6,0,0,0,4,1,1,0,0,1,1,E01002825,1,19,0,9,0,8,0,0,0,0,1,1,1,1,-1,-1,2143,2,4,-1,-1,-1
1,201501BS70002,526530.0,178560.0,-0.178838,51.491836,1,3,1,1,12/01/2015,2,07:50,12,E09000020,6,0,6,30,3,4,3,3218,0,0,1,1,1,0,0,1,1,E01002820,1,9,0,9,0,8,0,0,0,0,1,1,6,1,-1,-1,1600,1,3,-1,-1,-1
2,201501BS70004,524610.0,181080.0,-0.205590,51.514910,1,3,1,1,12/01/2015,2,18:08,12,E09000020,4,415,6,30,2,4,6,0,0,1,4,2,2,0,0,1,1,E01002833,1,9,0,9,0,2,0,0,0,0,1,1,6,1,30,6,1686,2,10,-1,1,-1
3,201501BS70005,524420.0,181080.0,-0.208327,51.514952,1,3,1,1,13/01/2015,3,07:40,12,E09000020,4,450,6,30,6,4,6,0,0,0,1,1,2,0,0,1,2,E01002874,1,9,0,9,0,2,0,0,0,0,1,1,6,1,-1,-1,-1,-1,-1,-1,-1,-1
4,201501BS70008,524630.0,179040.0,-0.206022,51.496572,1,2,2,1,09/01/2015,6,07:30,12,E09000020,3,315,6,30,6,2,3,3220,0,5,1,2,2,0,0,1,2,E01002814,1,1,0,18,0,8,0,0,0,0,0,1,2,1,48,8,-1,-1,-1,-1,1,-1

Below you can see that the datasets have successfull merged as there are a total of 54 columns. This is because the datasets have been merged on a common column (therefore 55-1).

In [10]:
print("Accidents_2015 dimensions: {}".format(Accidents_2015.shape))
print("Vehicles_2015 dimensions: {}".format(Vehicles_2015.shape))
print("All_2015 dimensions: {}".format(All_2015.shape))

Accidents_2015 dimensions: (140056, 32)
Vehicles_2015 dimensions: (257845, 23)
All_2015 dimensions: (227048, 54)

## 2.3 Check Datasets 2015 and 2016 Match

Next, we want to check that both of the 2015 and 2016 dataframes have the same columns. In order to check this we will create a list of the 2015 and 2016 column names and convert both of these lists to dataframes. We will then create a single dataframe containing the data from 2015 and 2016 and check that the column names match. This will make it easier for us to visualise the results and identify any errors in the dataset.

In [10]:
cols_2016 = list(All_2016.columns)
cols_2016_df = pd.DataFrame(cols_2016)

cols_2015 = list(All_2015.columns)
cols_2015_df = pd.DataFrame(cols_2015)

cols_2016_df[0].isin(cols_2015_df[0])

0     True
1     True
2     True
3     True
4     True
5     True
6     True
7     True
8     True
9     True
10    True
11    True
12    True
13    True
14    True
15    True
16    True
17    True
18    True
19    True
20    True
21    True
22    True
23    True
24    True
25    True
26    True
27    True
28    True
29    True
30    True
31    True
32    True
33    True
34    True
35    True
36    True
37    True
38    True
39    True
40    True
41    True
42    True
43    True
44    True
45    True
46    True
47    True
48    True
49    True
50    True
51    True
52    True
53    True
Name: 0, dtype: bool

In [11]:
# create a dataframe with the column names from both 2016 and 2015
joined = pd.DataFrame()
joined["cols_2016"] = cols_2016_df[0]
joined["2015_cols"] = cols_2015_df[0]

Where the column names match equal will be assigned to the 'equals' column in the corresponding row. Otherwise, 'not equal' will be assigned to it.

You can see below that they are all equal and therefore do not have a problem with the columns.

In [12]:
joined['equals'] = np.where(joined['cols_2016'] == joined['2015_cols'], 'equal', 'not equal')
joined

,cols_2016,2015_cols,equals
0,Accident_Index,Accident_Index,equal
1,Location_Easting_OSGR,Location_Easting_OSGR,equal
2,Location_Northing_OSGR,Location_Northing_OSGR,equal
3,Longitude,Longitude,equal
4,Latitude,Latitude,equal
5,Police_Force,Police_Force,equal
6,Accident_Severity,Accident_Severity,equal
7,Number_of_Vehicles,Number_of_Vehicles,equal
8,Number_of_Casualties,Number_of_Casualties,equal
9,Date,Date,equal
10,Day_of_Week,Day_of_Week,equal
11,Time,Time,equal
12,Local_Authority_(District),Local_Authority_(District),equal
13,Local_Authority_(Highway),Local_Authority_(Highway),equal
14,1st_Road_Class,1st_Road_Class,equal
15,1st_Road_Number,1st_Road_Number,equal
16,Road_Type,Road_Type,equal
17,Speed_limit,Speed_limit,equal
18,Junction_Detail,Junction_Detail,equal
19,Junction_Control,Junction_Control,equal
20,2nd_Road_Class,2nd_Road_Class,equal
21,2nd_Road_Number,2nd_Road_Number,equal
22,Pedestrian_Crossing-Human_Control,Pedestrian_Crossing-Human_Control,equal
23,Pedestrian_Crossing-Physical_Facilities,Pedestrian_Crossing-Physical_Facilities,equal
24,Light_Conditions,Light_Conditions,equal
25,Weather_Conditions,Weather_Conditions,equal
26,Road_Surface_Conditions,Road_Surface_Conditions,equal
27,Special_Conditions_at_Site,Special_Conditions_at_Site,equal
28,Carriageway_Hazards,Carriageway_Hazards,equal
29,Urban_or_Rural_Area,Urban_or_Rural_Area,equal
30,Did_Police_Officer_Attend_Scene_of_Accident,Did_Police_Officer_Attend_Scene_of_Accident,equal
31,LSOA_of_Accident_Location,LSOA_of_Accident_Location,equal
32,Vehicle_Reference,Vehicle_Reference,equal
33,Vehicle_Type,Vehicle_Type,equal
34,Towing_and_Articulation,Towing_and_Articulation,equal
35,Vehicle_Manoeuvre,Vehicle_Manoeuvre,equal
36,Vehicle_Location-Restricted_Lane,Vehicle_Location-Restricted_Lane,equal
37,Junction_Location,Junction_Location,equal
38,Skidding_and_Overturning,Skidding_and_Overturning,equal
39,Hit_Object_in_Carriageway,Hit_Object_in_Carriageway,equal
40,Vehicle_Leaving_Carriageway,Vehicle_Leaving_Carriageway,equal
41,Hit_Object_off_Carriageway,Hit_Object_off_Carriageway,equal
42,1st_Point_of_Impact,1st_Point_of_Impact,equal
43,Was_Vehicle_Left_Hand_Drive?,Was_Vehicle_Left_Hand_Drive?,equal
44,Journey_Purpose_of_Driver,Journey_Purpose_of_Driver,equal
45,Sex_of_Driver,Sex_of_Driver,equal
46,Age_of_Driver,Age_of_Driver,equal
47,Age_Band_of_Driver,Age_Band_of_Driver,equal
48,Engine_Capacity_(CC),Engine_Capacity_(CC),equal
49,Propulsion_Code,Propulsion_Code,equal
50,Age_of_Vehicle,Age_of_Vehicle,equal
51,Driver_IMD_Decile,Driver_IMD_Decile,equal
52,Driver_Home_Area_Type,Driver_Home_Area_Type,equal
53,Vehicle_IMD_Decile,Vehicle_IMD_Decile,equal

# 3. Aggregate 2015 and 2016 Dataframes
Here we will concatenate the 'All_2015' and 'All_2016' dataframes and will build a new index for this dataframe.

In [13]:
data_2015_2016 = pd.concat([All_2015, All_2016], ignore_index=True)
data_2015_2016.shape

(479548, 54)

To confirm that the data is correct we will check that the total number of rows in the individual datasets (All_2015 + All_2016) is the same as the combined dataset.

In [14]:
len(data_2015_2016) == len(All_2015) + len(All_2016)

True

# 4. Saving the Dataset

Above you can see that the datasets are matching. Therefore, we will select a subset of columns to save, since not all are needed or useful going forward.

In [19]:
data_2015_2016.columns # print existing columns

Index(['Accident_Index', 'Location_Easting_OSGR', 'Location_Northing_OSGR',
       'Longitude', 'Latitude', 'Police_Force', 'Accident_Severity',
       'Number_of_Vehicles', 'Number_of_Casualties', 'Date', 'Day_of_Week',
       'Time', 'Local_Authority_(District)', 'Local_Authority_(Highway)',
       '1st_Road_Class', '1st_Road_Number', 'Road_Type', 'Speed_limit',
       'Junction_Detail', 'Junction_Control', '2nd_Road_Class',
       '2nd_Road_Number', 'Pedestrian_Crossing-Human_Control',
       'Pedestrian_Crossing-Physical_Facilities', 'Light_Conditions',
       'Weather_Conditions', 'Road_Surface_Conditions',
       'Special_Conditions_at_Site', 'Carriageway_Hazards',
       'Urban_or_Rural_Area', 'Did_Police_Officer_Attend_Scene_of_Accident',
       'LSOA_of_Accident_Location', 'Vehicle_Reference', 'Vehicle_Type',
       'Towing_and_Articulation', 'Vehicle_Manoeuvre',
       'Vehicle_Location-Restricted_Lane', 'Junction_Location',
       'Skidding_and_Overturning', 'Hit_Object_in_Carriageway',
       'Vehicle_Leaving_Carriageway', 'Hit_Object_off_Carriageway',
       '1st_Point_of_Impact', 'Was_Vehicle_Left_Hand_Drive?',
       'Journey_Purpose_of_Driver', 'Sex_of_Driver', 'Age_of_Driver',
       'Age_Band_of_Driver', 'Engine_Capacity_(CC)', 'Propulsion_Code',
       'Age_of_Vehicle', 'Driver_IMD_Decile', 'Driver_Home_Area_Type',
       'Vehicle_IMD_Decile'],
      dtype='object')

In [16]:
cols_to_save = [
       'Accident_Index', 'Longitude', 'Latitude', 'Accident_Severity',
       'Number_of_Vehicles', 'Number_of_Casualties', 'Date', 'Day_of_Week', 
       'Time', 'Local_Authority_(District)', 'Road_Type', 'Speed_limit',
       'Junction_Detail', 'Light_Conditions','Weather_Conditions', 
       'Road_Surface_Conditions','Special_Conditions_at_Site', 
       'Urban_or_Rural_Area', 'Vehicle_Type', 'Vehicle_Manoeuvre', 
       'Vehicle_Location-Restricted_Lane', 'Journey_Purpose_of_Driver', 
       'Sex_of_Driver', 'Age_Band_of_Driver', 'Age_of_Vehicle', 
       'Driver_IMD_Decile', 'Driver_Home_Area_Type'
]

# 5. Saving Data to a Pickle File
Now we will save our combined dataset to a new file. We have chosen to save our data as a pickle file as we have such a large amount of data and it has the fastest save, and readtimes and a compact memory footprint.

In [17]:
pickle_save_time = %timeit -o data_2015_2016[cols_to_save].to_pickle("../../data/processed/200_all_2015-2016.pkl")  #save dataset into a pickle file and print the save time

pickle_save_time

1.8 s ± 46.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

# 6. Creating a Data Dictionary

In [18]:
data_dictionary.save(
    '../../data/processed/200_all_2015-2016.pkl', 

"""\
Aggregate raw data for UK Road Safety data for years 2015-2016.
""").head()

,count,unique,top,freq,mean,std,min,25%,50%,75%,max,Missing,%Missing
Accident_Index,479548,260293,201543P296025,37,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0.000000
Longitude,479483,NaN,NaN,NaN,-1.38182,1.38744,-7.42291,-2.25925,-1.31897,-0.19258,1.75844,65,0.013554
Latitude,479483,NaN,NaN,NaN,52.5624,1.39747,49.9156,51.5108,52.2473,53.4407,60.6611,65,0.013554
Accident_Severity,479548,NaN,NaN,NaN,2.83718,0.399757,1,3,3,3,3,0,0.000000
Number_of_Vehicles,479548,NaN,NaN,NaN,2.11341,0.894927,1,2,2,2,37,0,0.000000